### ISSUE TITLE
Why install python-psutil?

### ISSUE THREAD

**Issue by benzado** [DataDog/ansible-datadog#1]
Why does your task use `apt` to explicitly install `python-psutil`? Is it required by datadog, or merely optional? Should it have been included as a dependency of the datadog-agent package?

**Comment by benzado** [comment]
P.S. Thanks for sharing your work.

**Comment by bakins** [comment]
I use the data dog process monitor and `python-psutil` is required for it.  Could probably be removed or added to a different task file

**Comment by benzado** [comment]
OK, that makes sense. Thank you!

**Comment by bakins** [comment]
Your welcome.  Glad to see someone actually looking at the code besides me :)
