### ISSUE TITLE
Cannot start agent on Ubuntu 14.04

### ISSUE THREAD

**Issue by robertkern** [DataDog/ansible-datadog#10]
I installed the agent using this ansible role, but it failed at the step where it starts the agent with the following error:

```
 * Starting Datadog Agent (using supervisord) datadog-agent                                                                          [fail] 
error: <class 'httplib.IncompleteRead'>, IncompleteRead(3973 bytes read, 596 more expected): file: /opt/datadog-agent/embedded/lib/python2.7/httplib.py line: 705
Datadog Agent (supervisor) is NOT running all child processes
 * Stopping Datadog Agent (stopping supervisord) datadog-agent 
```

The same error is shown with `service datadog-agent start`.

It appears that some data has been sent to DataDog, and may still be sending.

**Comment by olivielpeau** [comment]
Hi @robertkern, thanks for reporting this issue!

If you see the same error when you start the agent manually, the issue probably comes from the agent itself and not this ansible role. In that case the best way to get help is to contact our support team directly (support@datadoghq.com) and attach the output of a [flare run](http://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command)

Thanks!

**Comment by olivielpeau** [comment]
@robertkern I'm closing the issue, feel free to re-open it with more info and/or contact our support team.
