### ISSUE TITLE
Hostname not complying with RFC 1123 should raise an error

### ISSUE THREAD

**Issue by nicgirault** [DataDog/ansible-datadog#100]
I struggled to understand why I did not have data on my datadog dashboard. The issue was that my hostname was not complying with RFC 1123. I suggest that the playbook fails in this case. I guess that dd-agent should also not be silent about this error (this is only a warning on version 1:5.12.3-1 `dd.collector[6935]: WARNING (hostname.py:35): Hostname: xxx is not complying with RFC 1123`).

**Comment by hush-hush** [comment]
Hi @nicgirault,

Both agents 5 and 6 will try to find the *best* hostname for your host. We first try to use the `hostname` from the configuration, then container/k8s/fargate/...,then cloud providers (AWS, GCP or Azure) and finally defaulting to the system hostname.

The first valid one will be used and if none are found/valid the agents will exit. That is why we only warn about the value from the configuration not being valid.

I would like to avoid duplicating the logic from both agents (which are slightly different as agent6 has a better support for containers).
In the meanwhile you raise a good point: should we exit when the value from the configuration file isn't valid ?

I will close this issue as it will not be solved in our Ansible role and will open an issue with the team to see if we should update the behaviour of the agent 6.

Thanks and feel free to reopen this issue if needed.
