### ISSUE TITLE
Upgrading ansible-datadog from 1.6.0 to 2.0.1 causes double APT repo entry

### ISSUE THREAD

**Issue by jharley** [DataDog/ansible-datadog#108]
Upgrading ansible-datadog from 1.6.0 to 2.0.1 on Ubuntu 16.04 (and presumably all other apt-based distributions) is causing a double entry in `/etc/apt/sources.list.d/apt_datadoghq_com.list` (one with `https` and one `http`).

This results in `apt-get update` failing due to the duplicate entry.

**Comment by ofirnn** [comment]
It also makes the role broken if you already have datadog5 agent installed (apt install wouldn't work), since the path changed to /etc/datadog-agent and it doesn't exists because the duplicate entry.

**Comment by jharley** [comment]
@ofirnn I was setting up the stuff to preserve the v5 agent after the APT key expiry (#103) forced me to upgrade to 2.0.1 of ansible-datadog.  Setting `datadog_agent5_apt_repo` back to the non-https value (as it was in ansible-datadog 1.6.0) fixes this issue if you keep the v5 agent

**Comment by anatolebeuzon** [comment]
Same issue here. I submitted a PR to fix this: #115

**Comment by excalq** [comment]
I made a similar fix to this issue, and waited until I could test it at work today. This ended up being PR #116 , but I see that you beat me to it, @oxlay. Well done.

**Comment by hush-hush** [comment]
This should be fix with the new version `2.0.3`, thanks to @oxlay and @excalq for their PR !
