### ISSUE TITLE
feature: support coreos

### ISSUE THREAD

**Issue by wallies** [DataDog/ansible-datadog#12]
this would use containers, so would take out the need to install packages

**Comment by olivielpeau** [comment]
Hi @wallies!

Are you referring to the setup of a containerized agent on a coreos host (i.e. what's described here: https://github.com/DataDog/docker-dd-agent#quick-start)?

**Comment by wallies** [comment]
@olivielpeau yes i am. I have it working in my fork for now. Going to continue testing it for now in my fork. Cheers

**Comment by hush-hush** [comment]
Closing this issue as we have no plan on supporting containers with ansible.
