### ISSUE TITLE
Add Datadog user to Docker user group, if applicable

### ISSUE THREAD

**Issue by rootd00d** [DataDog/ansible-datadog#130]
It seems like the Datadog agent process doesn't have enough permissions to inspect /var/run/docker.sock.  We've had to add a manual step to add the Datadog agent process user to the Docker group in order to enable using the Docker checks.

Adding this capability to the role would prove useful to us, and perhaps others trying to get their checks working properly.

**Comment by justinhoward** [comment]
Agreed, although on CentOS 7 the docker group is not available. See https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/. It would be nice to have a fix that works for RedHat-based linux as well.

**Comment by dabcoder** [comment]
Sorry for the delay in updating this thread, with version 3.0.0 of the role you can now add the `dd-agent` users to additional groups: https://github.com/DataDog/ansible-datadog/blob/master/CHANGELOG.md#300--2019-05-17. So that would cover the Debian based distributions, but I am not sure whether there is a workaround for CentOS 7.

**Comment by yiwork** [comment]
Is there documentation for this feature that I could check out?

**Comment by dabcoder** [comment]
We've added this var to the README: https://github.com/DataDog/ansible-datadog#role-variables.

**Comment by dabcoder** [comment]
@justinhoward I did a bit of research on that issue, on CentOS 7, it looks like you can manually create a `docker` group and change the group ownership of the `docker.sock` to that `docker` group. 
You can then add the `dd-agent` user to the `docker` group with the role variable `datadog_additional_groups`. 

I am going to close this issue for now but let us know if this needs to be reopened should you have any additional feedback to provide.

**Comment by justinhoward** [comment]
@dabcoder Yes, I assumed you can manually create the group, but bypassing the security put in place by the distro seems like a bad idea. If you read Dan Walsh's article, he makes a pretty good case.

Regardless, I'm not using datadog with ansible on CentOS any longer, so I won't push the issue. Thanks for looking into it.

**Comment by dabcoder** [comment]
> Yes, I assumed you can manually create the group, but bypassing the security put in place by the distro seems like a bad idea. If you read Dan Walsh's article, he makes a pretty good case.

Sure, I was by no mean suggesting this workaround as steps that users _should_ do. Thanks for following up too!
