### ISSUE TITLE
Allow multiple config file per check

### ISSUE THREAD

**Issue by hush-hush** [DataDog/ansible-datadog#133]
Right now a check will be configured in `conf.d/<check>.d/conf.yaml`. This behavior might be an issue when people are using autodiscovery. Customer might have multiple containers for one check needing different configuration.

Bottom line: this role should allow customer to overwrite the file name of the configuration.

**Comment by kzap** [comment]
you can also use ansible to put your own config files in the right directory

**Comment by yiwork** [comment]
The customer should be able to leverage the `tasks/post_tasks/main.yml` file to achieve what they want. Post installation customers can use that file to specify additional conf files to generate and rename to the main config.
