### ISSUE TITLE
logs enabled

### ISSUE THREAD

**Issue by ladean** [DataDog/ansible-datadog#142]
Hi,

Not really an issue anymore for me, but I was trying to enable Datadog Logs in the agent. The flag `logs_enabled: True` was not getting added to the datadog.yaml config file after running the playbook.

I've added the following to roles/ansible-datadog/templates/datadog.yaml.j2 

```
{% if datadog_config["logs_enabled"] is not defined -%}
logs_enabled: {{ datadog_logs_enabled | default('false') }}
{% endif %}
```

 I've placed the variable  ` - datadog_logs_enabled: true` in my playbook.

Hope this might help someone else out.

Thanks,
Ladean

**Comment by hush-hush** [comment]
Hi @ladean,

Did you set `logs_enabled: True` in the `datadog_config` dict ? Like in this example: https://github.com/DataDog/ansible-datadog#example-playbooks

I tried to reproduce the issue but it worked for me with the latest version of the role. Which version of `ansible-datadog` are you using ?

**Comment by ladean** [comment]
Hi @hush-hush 

Thanks for your link, I missed this somehow. It is working correctly for me as per the example.

**Comment by hush-hush** [comment]
Glad to here it !

Closing the issue then.
