### ISSUE TITLE
Role always restarts Datadog because of old workaround

### ISSUE THREAD

**Issue by kcd83** [DataDog/ansible-datadog#147]
The following is bad practice and mean ansible _always_ thinks it has changed and always fires the restart handler despite `--check` mode showing no changes.

```
command: yum install -y datadog-agent
```
That was implemented to workaround to https://github.com/ansible/ansible/issues/20608 which is now resolved.

This PR fixes this, please take a look #144

**Comment by dabcoder** [comment]
Closing this since it was addressed in #199.
