### ISSUE TITLE
url whitelist in closed network for all os.

### ISSUE THREAD

**Issue by sandy-una** [DataDog/ansible-datadog#162]
what url need to be whitelisted to download the installation package from the internet under this ansible role?

**Comment by hush-hush** [comment]
Hi @sandy-una,

It depends on the OS you're using. On Linux we use the package manager for the install:
- suse/yum: `https://yum.datadoghq.com`
- debian/ubuntu: `https://apt.datadoghq.com`

On windows we download the MSI from `https://s3.amazonaws.com/ddagent-windows-stable`.

Those URL can be changed through if you want to use a proxy or package cache: https://github.com/DataDog/ansible-datadog/blob/master/defaults/main.yml

The role uses the same URL than the installation instruction from the website if you want to know more: https://app.datadoghq.com/account/settings#agent.

Closing this issue but feel free to reopen if needed.
