### ISSUE TITLE
Failed to install GPG key on Debian

### ISSUE THREAD

**Issue by juniorh** [DataDog/ansible-datadog#184]
Installation agent by single command sometimes failed due to GPG installation issue. 

> $ DD_API_KEY=XXXXX bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"
> ...
> Executing: /tmp/apt-key-gpghome.hl6ODRyImw/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 382E94DE
> gpg: keyserver receive failed: No keyserver available
> ...

Agent installaion is failed if GPG installation failed. In other hand we have other option to install GPG by this command

> wget -O - "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD3A80E30382E94DE" | apt-key add -

**Comment by dabcoder** [comment]
@juniorh sorry for the delay in updating this thread. Are you still experiencing this issue? Note that there is a possibility to use a backup keyserver: https://github.com/DataDog/ansible-datadog/blob/master/defaults/main.yml#L20.
