### ISSUE TITLE
ansible_facts.env['ProgramData'] not working for 2012R2 - should be ansible_env.ProgramData instead

### ISSUE THREAD

**Issue by ncracker** [DataDog/ansible-datadog#190]
File tasks/agent6-win.yml contains a few tasks which try to make use of Windows ENV for ProgramData. It does not work the way it's being referenced currently...

e.g. line 5
`dest: "{{ ansible_facts.env['ProgramData'] }}\\Datadog\\datadog.yaml"`
should actually be
`dest: "{{ ansible_env.ProgramData }}\\Datadog\\datadog.yaml"`

This pattern repeats a few time always erroring out with FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_facts' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/Datadog.datadog/tasks/agent6-win.yml'

@jaycdave88  and I tested extensively. Works well with ansible_env.ProgramData

We'll test 2008, 2016 & 2019 also to verify that would work there as well and PR it

**Comment by ncracker** [comment]
Forgot to mention - issue observed with Ansible 2.4.2

**Comment by dabcoder** [comment]
@ncracker Thanks for reporting this. Did you manage to test it on the aforementioned Windows versions?

**Comment by dabcoder** [comment]
cc @jaycdave88. Let us know when you have an update on your testing for this one.

**Comment by dabcoder** [comment]
Closing this as this is no longer an issue with ansible > 2.4.2.
