### ISSUE TITLE
Possibility to change api url

### ISSUE THREAD

**Issue by local-master** [DataDog/ansible-datadog#192]
Hi,

I am facing an issue when using the DataDog_monitor module for Ansible. I am want to deploy monitors using the Ansible but I have my own custom api url not the default one "https://api.datadoghq.com/api/"  I've tried using "Enviroment" function in Ansible and add "DATADOG_HOST:" which solved the authentication issue I had but still can't add monitors due to errors.

**Comment by dabcoder** [comment]
Hello,

The issue you are facing is related to the community module (https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/monitoring) on the ansible repository (which we do not maintain). You may want to open an issue there with some additional details about your configuration.
