### ISSUE TITLE
feature: allow adding tags

### ISSUE THREAD

**Issue by stefanfoulis** [DataDog/ansible-datadog#2]

**Comment by bakins** [comment]
What kind of tags?  Agent level tags or??

**Comment by olivielpeau** [comment]
Agent-level tags can be added through the `datadog_config` variable (see the examples in the README).
The agent checks that support custom tags can also be configured fully, so it shouldn't be an issue either.

Closing this issue, @stefanfoulis feel free to add some details if my answer doesn't address what you were thinking of. Thanks!
