### ISSUE TITLE
Feature request: add support for post-install custom tasks

### ISSUE THREAD

**Issue by yiwork** [DataDog/ansible-datadog#202]
Currently inside the datadog ansible role, there's no way to add custom post install tasks without having to fork the repo:

Suggestion, add a post_task folder to include all other tasks that might need to be invoked after main configuration:

in `datadog-datadog` role main task, modify to be the following
```
- include: agent6.yml
  when: not datadog_agent5

- include: post_tasks/*.yml
```

Make certain that post_task is git-ignored so we can keep pulling updates without needing to fork the repo, and still have the role perform other tasks post config/install. 

Perfect use-case:
https://github.com/DataDog/ansible-datadog/issues/130

Not everyone needs docker integration, but if you do, all customers need to do is to create a new task definition in `post_tasks` folder to add datadog-agent user to the docker group. 

I could see as well a `pre_tasks` folder being useful as well, to prepare for datadog role invocation.

**Comment by dabcoder** [comment]
Thanks for the detailed information.

> Currently inside the datadog ansible role, there's no way to add custom post install tasks without having to fork the repo:

True, but shouldn't these `post_tasks` and `pre_tasks` be handled at the playbook level and not at the role level? Or am I missing something there?

By the way [unrelated], for #130, we've added an option to add the `dd-agent` user to other user defined groups.

**Comment by yiwork** [comment]
`True, but shouldn't these post_tasks and pre_tasks be handled at the playbook level and not at the role level? Or am I missing something there?`

Yup, I am asking that we borrow an idea from playbook and using it in a role. This will make datadog role a lot more flexible for your customers during deployment, without having to remember to always include certain tasks in playbooks. 

For example - I'm leveraging datadog socket file to send datadog metrics. For every single playbook, I always have to remember(aside from adding datadog to docker group), to create the socket file. 

Another example - for some legacy servers that I have (that I cannot just rebuild from scratch), I have to conduct some cleaning up prior to invoking the role. 

Given how Datadog is increasingly adding new features (which is great), and are centralizing the deployment of all those products upon the deployment and customization of just one agent. I think this would make your role a lot easier to use and update.

**Comment by yiwork** [comment]
FWIW - this feature would help us solve https://github.com/DataDog/ansible-datadog/issues/43 without having you guys get involved. 

So is this one - https://github.com/DataDog/ansible-datadog/issues/73 we could easily taken care of this one ourselves by adding a simple task in the `post_tasks` folder, and again, key being without having getting you guys involved. 

The total amount of work on your part right now to get this done would be adding those lines I posted above, then bash commands `mkdir post_tasks; touch post_tasks/README; git add post_tasks/README; git commit`, and it would solve so many issues that your customers can take care of ourselves without requesting upstream changes, i.e. work from you guys.

**Comment by dabcoder** [comment]
Added support for this in #204, thanks @yiwork
