### ISSUE TITLE
The trace-agent.conf and process-agent.conf files aren't needed in agent6 tasks

### ISSUE THREAD

**Issue by chadnetzer** [DataDog/ansible-datadog#206]
The agent6-linux.yml and agent6-win.yml tasks still install both the trace-agent.conf and process-agent.conf files, even though they are not used (afaict) in v6, and in fact will be improperly formed when generated from the datadog.conf.j2 template which now uses YAML for the datadog_config (and which gets rendered incorrectly as Python objects in the template, when using YAML nested dictionaries, etc.)  These unused files create confusion because ansible shows them as updating with clearly bogus results when changing/adding-to the datadog_config YAML variable.

The .conf install tasks should be removed from tasks/agent6-linux.yml, possibly with some deprecation message for those who don't realize they need to migrate their config over to datadog_config.

**Comment by KSerrania** [comment]
#272 fixes this problem, closing this issue.
