### ISSUE TITLE
Failing task: [Datadog.datadog : Ensure datadog-agent-sysprobe is running if enabled and installed]

### ISSUE THREAD

**Issue by OldCrowEW** [DataDog/ansible-datadog#214]
It seems like https://github.com/DataDog/ansible-datadog/commit/27b07cf4eafd690a01efc4a21165afcaac177c47 has broken `master`. We are seeing the following error today:
```
TASK [Datadog.datadog : Ensure datadog-agent-sysprobe is running if enabled and installed] ***************************************************************************************************************************************************
Thursday 17 October 2019  08:33:35 -0400 (0:00:00.149)       0:00:54.228 ******
fatal: [host.internal.com]: FAILED! => {}

MSG:

The conditional check 'not datadog_skip_running_check and datadog_enabled and not ansible_check_mode and datadog_sysprobe_enabled' failed. The error was: error while evaluating conditional (not datadog_skip_running_check and datadog_enabled and not ansible_check_mode and datadog_sysprobe_enabled): 'datadog_sysprobe_enabled' is undefined

The error appears to have been in '~/ansible/galaxy_roles/Datadog.datadog/tasks/agent6-linux.yml': line 84, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure datadog-agent-sysprobe is running if enabled and installed
  ^ here


fatal: [host.internal.com]: FAILED! => {}
```
This is likely a duplicate of:

- https://github.com/DataDog/ansible-datadog/issues/212
- https://github.com/DataDog/ansible-datadog/issues/213

Current workaround is to set galaxy role to prior commit and everything behaves as expected.

**Comment by hush-hush** [comment]
Hi @OldCrowEW,

Thanks for opening this issue. This should be fix with the latest commit on master.
As a general rule we don't advise on using master for the ansible role as some feature still in beta might be present. I'll suggest to use the latest tagged version (3.2.0 right now) or to use ansible-galaxy.

I'm closing this issue but feel free to reopen it if needed !

**Comment by OldCrowEW** [comment]
thx @hush-hush !
