### ISSUE TITLE
Tags not working as expected

### ISSUE THREAD

**Issue by rosario-raulin** [DataDog/ansible-datadog#216]
I have a problem with adding host tags via the `datadog_confg` variable.

## What I do

Is set the `datadog_config` variable to:

```
    datadog_config:
      tags:
        - datacenter: mydatacenter
```

as is documented [here](https://github.com/DataDog/ansible-datadog#example-playbooks).

## What should happen

I'd expect a config line being generated as follows:

```
tags:
  - datacenter:mydatacenter
```
In turn I'd see my host using the host tag `datacenter:mydatacenter`.

## What actually happens

The following config line is generated:
```
tags:
-   datacenter: mydatacenter
```

In turn this tag does not appear at all in Datadog.

This looks like a bug to me or am I misunderstanding something?

**Comment by blackstar257** [comment]
Same

**Comment by robstar** [comment]
The resulting yaml is perfectly valid, its just a different kind of indentation. 

To solve your problem, just remove the space after `datacenter:` and make it
```
tags:
  - datacenter:mydatacenter
```
Doing so will result in each list item being interpreted as a scalar. Once you include a space afterwards it is a mapping of scalars to scalars instead which doesn't work as a tag here.

**Comment by blackstar257** [comment]
Should probably update your README.md 

https://github.com/DataDog/ansible-datadog/commit/229362688669e4357a52f457f85323e8d6a1d817
