### ISSUE TITLE
TASK [Datadog.datadog : Create system-probe configuration file] Failure

### ISSUE THREAD

**Issue by omur-deltadna** [DataDog/ansible-datadog#229]
Hello, 

I started getting the following message, we didn't change anything in our config or playbook. Would that be related to any of your recent changes?

googlecompute: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on (# Managed by Ansible\n\n{% if system_probe_config is defined and system_probe_config|length > 0 -%}\nsystem_probe_config:\n{% filter indent(width=2, first=True) %}\n{{ system_probe_config | to_nice_yaml }}\n{% endfilter %}\n{% endif %}\n): do_indent() got an unexpected keyword argument 'first'"}

Thanks

**Comment by alexkinch** [comment]
Same here, during TASK [Datadog.datadog : Create system-probe configuration file]. Changing `first` to `indentfirst` in `templates/system-probe.yaml.j2` fixed it for me, but ymmv.

**Comment by stefanux** [comment]
the parameter indent (before: "indentfirst") was introduced in jinja2 version 2.10 (https://jinja.palletsprojects.com/en/master/templates/#indent ). so this work on current jinja2 version but not in older environment (centos 7, debian 8, ubuntu 16.04).

**Comment by margeson** [comment]
I ran into the same issue on Ubuntu 16.04. You can solve this by performing the following:

`sudo apt install python-pip`
`sudo pip install pip --upgrade`
`sudo pip install jinja2 --upgrade`

**Comment by KSerrania** [comment]
Support for jinja versions < 2.10 in the system-probe jinja template was added back in bugfix releases 4.0.1 and 3.4.1 (by using `indentfirst` instead of `first`).
