### ISSUE TITLE
bsd based systems are not detected or supported

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/ansible-datadog#231]
While I was able to successfully use this role to deploy DataDog Agent on CentOS 8 and RHEL8, I cannot say the same about:

* Synology DSM
* OpnSense (pfsense derivative).
* MacOS

I can fully understand that they may not be supported yet. Still, they should be detected and deployment should raise a failure explaining that, preferably pointing to a feature request to add support for them. Doing this could raise awareness about how many people do want to use this ansible role to deploy-datadog on these platforms.

Note: I am considering adding support for them myself if there are no other deal breakers that would make the task impossible.

**Comment by albertvaka** [comment]
We do release the Agent for MacOS, so we could support it on Ansible. This is the first time we see such feature request, though, so it's not a high priority.

For OSes where we do not offer official builds of the Agent, all we can do is to log an error. It should be a catch-all (ie: not have an entry for every OS we don't support).

It is indeed a good idea to track demand, so we could add a link to the https://github.com/DataDog/datadog-agent repo issues from that log.

**Comment by KSerrania** [comment]
Hi @ssbarnea and @albertvaka,

Thanks for the report! We recently published version 4.1.0 of the role which contains this PR: https://github.com/DataDog/ansible-datadog/pull/247, to make sure that users have an explicit error message when their OS is not supported & have a sense of which are the platforms most requested.
We currently redirect the users to our support address, but we could change that if there are better places to keep track of demand.

**Comment by dpippen** [comment]
I'd like to see MacOS support added to Ansible.  There are probably a lot of Datadog users maintaining mac jenkins workers to run Xcode for IOS builds.  I'm starting to use the new AWS ec2 macs and having a clean ansible solution for deploying Datadog just got a lot more urgent.

**Comment by albertvaka** [comment]
Hi @dpippen! Thanks for your input :) We are tracking MacOS support as a feature request internally and measuring demand for it. As you mention, we also would expect more users now that AWS added support for MacOS instances.

**Comment by jdeveloperw** [comment]
+1 For OS X support.

Datadog is such a great tool, and easy to install and use. Thank you for all of the work you do!

**Comment by tejassharma96** [comment]
+1 for MacOS support

**Comment by alopezz** [comment]
This seems to have been fixed by https://github.com/DataDog/ansible-datadog/pull/437.
