### ISSUE TITLE
[DEPRECATION WARNING]: ...datadog_checks.keys()

### ISSUE THREAD

**Issue by oharlem** [DataDog/ansible-datadog#25]
Hi guys,

Using Ansible 2.0.2.0 to deploy to Debian 8.4.
Getting this:

> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax
> ('{{datadog_checks.keys()}}').
> This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in
>  ansible.cfg.

Thank you!

**Comment by olivielpeau** [comment]
Hi @mpmlj!

This issue is a duplicate of #14, which has been fixed through #21 and released with `1.0.0`. Closing.
