### ISSUE TITLE
How can i make this work with centify and dzdo

### ISSUE THREAD

**Issue by murali-krishnamoorthy** [DataDog/ansible-datadog#253]
we are using centrify and hence we cannot use sudo. We use dzdo .
1. Does the role work with dzdo instead of sudo .

**Comment by danielsimkus** [comment]
I don't know much about centrify, but as far as I can tell, this plugin makes no direct references to the sudo command specifically.

Have you tried using this on your playbook? `become_exe: dzdo`
https://docs.ansible.com/ansible/latest/plugins/become/dzdo.html

**Comment by jeremy-lq** [comment]
Thanks, Daniel. This should work as expected, @murali-krishnamoorthy. If it doesn't please open a support ticket, with any errors you receive.
