### ISSUE TITLE
I can't install datadog in ubuntu server (with ansible)

### ISSUE THREAD

**Issue by caioleitao** [DataDog/ansible-datadog#279]
datadog-agent status error: Error: unable to read authentication token file: open /etc/datadog-agent/auth_token: no such file or directory

help me

**Comment by ian28223** [comment]
that error means that datadog agent is installed but someone started the agent not as `dd-agent` user (did not use `systemctl` or `service`). Just delete the file `/etc/datadog-agent/auth_token` then restart the agent using `systemctl start datadog-agent` or `service datadog-agent start`

**Comment by caioleitao** [comment]
thanks! its works! :D

**Comment by caioleitao** [comment]
thanks
