### ISSUE TITLE
DataDog Ansible Galaxy Role v4.3.0 missing

### ISSUE THREAD

**Issue by carflo** [DataDog/ansible-datadog#292]
It appears that https://galaxy.ansible.com/DataDog/datadog hasn't been updated with the latest 4.3.0 release of the role despite the release being cut 3 months ago. 

Can you publish an update so that we can install the latest DataDog Agent?

**Comment by KSerrania** [comment]
Hi @carflo,

Thanks for pointing this out! I published 4.3.0 on ansible-galaxy a few minutes ago, so you should be able to pull it now.

**Comment by carflo** [comment]
@KSerrania Thank you!!
