### ISSUE TITLE
yum module is not supported with Python 3

### ISSUE THREAD

**Issue by xkrt** [DataDog/ansible-datadog#298]
Hi!

[Documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html) of Ansible's `yum` module says:
> This module only works on Python 2. If you require Python 3 support see the dnf module.

but `ansible-datadog` uses `yum` unconditionally, see https://github.com/DataDog/ansible-datadog/blob/cc9179510369fd2fccdac3403f73394cbd06e0ef/tasks/pkg-redhat/install-pinned.yml#L3 and https://github.com/DataDog/ansible-datadog/blob/cc9179510369fd2fccdac3403f73394cbd06e0ef/tasks/pkg-redhat/install-latest.yml#L3

Python 2 was [retired](https://www.python.org/doc/sunset-python-2/) at January 1, 2020 and I'm working on switching to Python 3 as probably many others.

I believe `ansible-datadog` should use `dnf` module instead of `yum` if the current interpreter is 3.

**Comment by KSerrania** [comment]
Hi @xkrt!

Thanks for the report, and sorry for the (very) late answer! I opened #301 which should fix this issue. Feel free to comment if you think there's anything that could be improved there!
