### ISSUE TITLE
AWX Project update fails due to bad datadog version

### ISSUE THREAD

**Issue by Jacko161** [DataDog/ansible-datadog#306]
Hi!

As of this morning, we have started seeing the following failure when running a project update on our AWX system. We found a newly released datadog version may be the culprit. 

```
"stderr_lines": [
        "[WARNING]: - Datadog.datadog was NOT installed successfully: Unable to compare",
        "role versions (1.2.0, 2.1.0, v4.4.0, 1.3.0, 3.3.0, 1.6.0, 1.6.1, 2.4.0, 2.0.2,",
        "3.2.0, 2.0.1, 4.3.0, 4.2.0, 2.0.3, 3.4.0, 2.5.0, 2.3.1, 4.2.1, 3.0.0, 2.3.0,",
        "2.0.0, 4.1.1, 2.6.0, 3.1.0, 1.1.0, 4.0.1, 4.1.0, 4.0.0, 1.4.0, 1.5.0, 3.4.1,",
        "1.0.0, 2.2.0) to determine the most recent version due to incompatible version",
        "formats. Please contact the role author to resolve versioning conflicts, or",
        "specify an explicit role version to install.",
        "ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list."
]
```

We currently do not specify a version of datadog to pull, so we are going to try that but it seems like the automatic resolution of versions is broken currently for Datadog.

**Comment by KSerrania** [comment]
Hi @Jacko161,

Thanks for the report!

Indeed, the latest version of the role was mistakenly tagged `v4.4.0` instead of `4.4.0`, which confused the automatic resolution of versions. I removed that tag and re-tagged `4.4.0`, so this should be fixed now.
