### ISSUE TITLE
Support for Custom Check scripts

### ISSUE THREAD

**Issue by pliops-jonathane** [DataDog/ansible-datadog#315]
We are able to add custom_check yamls when deploying but we need the python scripts for them.
We would like the option to copy .py files with the same name as the script to checks.d folder.
It is essential that the script files will be copied with the same process because Datadog requires a restart.

**Comment by albertvaka** [comment]
I understand that the Agent must be restarted after the python files have been copied, but can't you first copy the python files, then configure the Agent `datadog_checks`?  This will trigger the Agent restart after the files are already there.

An alternative would be to first create the checks' config and afterwards copy the files with `notify: restart datadog-agent` but that will cause the Agent to restart twice.

I think the above alternatives are simple enough and should work out of the box, so I'm not sure we need explicit support to deploy custom check scripts.

**Comment by pliops-jonathane** [comment]
Thanks for the answer, 
I did the second option, but I think it is better to support it as part of the role with some kind of list variable.
If you are not intending to support this issue, it can stay for documentation.

**Comment by spr0ut** [comment]
If nothing else the documentation should make this need to have a separate task to copy the files explicit, though I feel there should be something baked in to support this.

**Comment by mtb-xt** [comment]
@albertvaka  the problem with copying python files first, is that on a fresh installation there would be no `datadog-agent/checks.d` directory. We would have to precreate it, but dd-agent user is also absent at that point. Of course, all that could be worked around, but it would be much easier if the role supported uploading custom checks.
Would you be willing to accept PRs for this functionality?

**Comment by albertvaka** [comment]
We are happy to accept patches :)
