### ISSUE TITLE
Option for skipping "Downloading new RPM keys" (disable gpgcheck)

### ISSUE THREAD

**Issue by raj707** [DataDog/ansible-datadog#322]
We are using our own internal yum repo for downloading Datadog-agent. Gpgcheck is disabled for our repo i.e it does not have a gpgkey. However there is no option in Datadog role for disabling gpgcheck. Hence the following task is failing for us:

TASK [datadog.datadog : Download new RPM key (Expires in 2022)] *********************************************************************************************************************************
fatal: [host]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for yum.datadoghq.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.6.6 or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:492: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol.", "status": -1, "url": "https://yum.datadoghq.com/DATADOG_RPM_KEY_E09422B3.public"}
*********************************************************************************************************************************

---> Can you guys provide a way to skip/disable downloading RPM keys when the custom yum repo has gpgcheck disabled.

**Comment by albertvaka** [comment]
I think it makes sense to add this feature, since we allow customizing the repo URL. Adding this to our backlog.
