### ISSUE TITLE
Used conf.yaml.default instead of the created conf.yaml

### ISSUE THREAD

**Issue by acurvers** [DataDog/ansible-datadog#355]
IIt seems datadog-agent checks uses the conf.yaml.default for the checks
and the checks conf.yaml that is added by the ansible playbook is not loaded, even tho its in the correct directory for example
`/etc/datadog-agent/conf.d/disk.d/conf.yaml`
is this a bug, or do i need to change something?

**Comment by acurvers** [comment]
nevermind seems the conf was invalid and then not picked up but conf.yaml.default used

**Comment by bkabrda** [comment]
Thanks for opening the issue and updating with what caused the problem. IIUC there's nothing to be done here, so I'm closing it now - feel free to open a new one if you have more problems. Thanks!
