### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by jurschel** [DataDog/ansible-datadog#365]
Can I use this role to uninstall DataDog?

**Comment by bkabrda** [comment]
Hi 👋 thanks for raising this question. This is currently not possible, but I've added a task on our team's backlog to look into this. I'll update this issue when we get to it - we don't have any specific date right now.

**Comment by mriddell-foundry** [comment]
Is there any update on this feature?

**Comment by bkabrda** [comment]
Hi @mriddell-foundry not yet, but giving a 👍 to the root comment would certainly help us understand how much this is requested and hence prioritize it properly.

**Comment by alopezz** [comment]
This is now tracked in the more recent https://github.com/DataDog/ansible-datadog/issues/508, I'll close this.
