### ISSUE TITLE
Hostname is changed from hostname fqdn to hostname after datadog role upgrade

### ISSUE THREAD

**Issue by edvinas31** [DataDog/ansible-datadog#381]
Hello, we are using ansible to install datadog on our hosts. Upgrading datadog ansible role for many instances were not a problem. However, after upgrading datadog ansible role from 4.6.0 to 4.11.0 for docker instance we found out that hostname in inventory list changed from hostname fqdn to hostname. For example `custenv-dock01.dock.custenv.oraclevcn.com` to `custenv-dock01`. I have noticed that `datadog-agent status` command on not affected machines metadata section shows `"hostname_source: fqdn"` but on the docker ones it shows `"hostname_source: container"`. What should be done to revert back and use fqdn instead of hostname on docker instances?

**Comment by edvinas31** [comment]
Pasting our playbook, which calls the role:

>     ### Monitoring
    - name: Install datadog agent
      include_role:
        name: datadog.datadog
        apply:
          tags:
            - datadog
      vars:
        datadog_api_key: "{{ credentials_vault['datadoghq.eu'].api_key }}"
        datadog_site: "datadoghq.eu"
        datadog_agent_major_version: "6"
        datadog_config:
          process_config:
            enabled: "true"
          hostname_fqdn: true
          tags:
            - client:{{ cust_name }}
            - env:{{ oci_tag_env_type }}
            - os:linux:{{ ansible_facts.distribution }}
      when:
      - cust_name is defined
      - oci_tag_env_type is defined
      - not ansible_facts.distribution_major_version == '6' # Python 2.6 prevents this role from working correctly.
      tags: datadog

**Comment by edvinas31** [comment]
sudo datadog-agent status command 

```
...

  Hostnames
  =========
    hostname: paasdev-dock01
    socket-fqdn: paasdev-dock01.dock.paasdev.oraclevcn.com.
    socket-hostname: paasdev-dock01
    host tags:
      client:paas
      env:dev
      os:linux:OracleLinux
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance and other providers already retrieve non-default hostnames
      azure: azure_hostname_style is set to 'os'
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

  Metadata
  ========
    hostname_source: container
...
```

**Comment by edvinas31** [comment]
Looking at the datadog-agent code we can see a hostname providers order: https://github.com/DataDog/datadog-agent/blob/main/pkg/util/hostname.go

First it tries to query docker for a hostname retrieval and only after that operating system

**Comment by KSerrania** [comment]
Hi @edvinas31,

Thanks for the report!

I'd like to ask you a few things to get some more context:
- Could you provide us what Agent version is running on both the non-affected and the affected hosts?
- On affected hosts, can you check in the main configuration file (`/etc/datadog-agent/datadog.yaml`) that the `hostname_fqdn: true` option is correctly set?
- Do you also know which Agent version was installed before you did the upgrade that changed the hostname resolution?

**Comment by edvinas31** [comment]
Hi, @KSerrania 

1) Agent version on both afftected and non-affected hosts is the same:
```
$ sudo datadog-agent version
Agent 6.30.0 - Commit: 2d834aa - Serialization version: v4.78.0 - Go version: go1.15.13
```
2) The main configuration file `/etc/datadog-agent/datadog.yaml `on affected hosts is like this:
```
# Managed by Ansible

site: datadoghq.eu


api_key: xxxxxxxxxxxxxxxx

hostname_fqdn: true
process_config:
    enabled: 'true'
tags:
- client:paas
- env:dev
- os:linux:OracleLinux
```
3) Previous agent version:
```
$ sudo datadog-agent version
Agent 6.25.1 - Commit: a6233aa - Serialization version: v4.49.0 - Go version: go1.14.12
```

**Comment by KSerrania** [comment]
Hi again,

**Note:** If the API key in the configuration you pasted is real, I strongly recommend removing it from your post & [revoking it in your Datadog account](https://docs.datadoghq.com/account_management/api-app-keys/#remove-api-keys-or-client-tokens), to prevent other users from using it.

To check whether this issue is due to the Agent version or the ansible-datadog version, could you revert to the previous Agent version on your hosts? To do so, you can amend your playbook and add:
```
  vars:
    ...
    datadog_agent_version: "6.25.1" # Pin the Agent version
    datadog_agent_allow_downgrade: yes # Allow the role to downgrade the Agent from 6.30.0 to 6.25.1
```

which should make the role install `6.25.1` on your hosts.

**Comment by edvinas31** [comment]
After I have added lines below to my playbook hostname went back to the one we want:
```
  vars:
    ...
    datadog_agent_version: "6.25.1" # Pin the Agent version
    datadog_agent_allow_downgrade: yes # Allow the role to downgrade the Agent from 6.30.0 to 6.25.1
```

**Comment by vboulineau** [comment]
Hello @edvinas31,

It's probably because new Agent version auto detected Docker setup and started using it as a hostname provider.
Normally it means you were not using Docker integration before, in which case you can disable it by setting: `DD_AUTOCONFIG_EXCLUDE_FEATURES=docker` or `autoconfig_exclude_features: ["docker"]`

**Comment by edvinas31** [comment]
Hi @vboulineau actually I was willing to use Docker integration on a docker instance type machine. And most of my machines were already using it successfully

**Comment by vboulineau** [comment]
I understood the issue, I'll ship a fix with `7.31.0`.

**Comment by bkabrda** [comment]
@vboulineau was the fix that you mentioned in the last comment shipped in 7.31.0? Thanks!

**Comment by vboulineau** [comment]
Yes, was fixed by https://github.com/DataDog/datadog-agent/pull/8949

**Comment by bkabrda** [comment]
@edvinas31 could you please try to use 7.31.0 and see if that helps you? Thanks!

**Comment by alopezz** [comment]
From the thread above and the lack of further response I'm going to assume this has already been fixed; closing as such.
