### ISSUE TITLE
Permission denied on apt-get when using datadog role

### ISSUE THREAD

**Issue by ollyculverhouse** [DataDog/ansible-datadog#39]
I am seeing an issue with the datadog role where it is failing due to apt-get not being available. Below is the output from ansible:

```
TASK [Datadog.datadog : apt] ***************************************************
ok: [52.56.74.57]

TASK [Datadog.datadog : apt_key] ***********************************************
changed: [52.56.74.57]

TASK [Datadog.datadog : apt_key] ***********************************************
skipping: [52.56.74.57]

TASK [Datadog.datadog : apt_key] ***********************************************
changed: [52.56.74.57]

TASK [Datadog.datadog : apt_key] ***********************************************
skipping: [52.56.74.57]

TASK [Datadog.datadog : apt_repository] ****************************************
changed: [52.56.74.57]

TASK [Datadog.datadog : apt] ***************************************************
fatal: [52.56.74.57]: FAILED! => {"cache_update_time": 1482931915, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'datadog-agent'' failed: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)\nE: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?\n", "stderr": "E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)\nE: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?\n", "stdout": "", "stdout_lines": []}
```

It definitely has sudo permission as the same playbook performs other tasks. 
Could it be because the previous apt_repository task hasn't completed?

I have just manually added a pause task (http://docs.ansible.com/ansible/pause_module.html), inbetween apt_repository and apt (for 30 seconds, just to test) and everything goes through correctly and installs. Looks like that was it!

For your reference I am running Ubuntu 16.04.1 LTS.

Hope that helps?

**Comment by olivielpeau** [comment]
Hi @ollyculverhouse, thanks for reporting this issue!

Just so I'm sure I understand, did this issue happen consistently in your first few runs of the role?
Also, which version of Ansible are you running?

As you said this could come from `apt_repository` not completing properly before the package install is run, I'd like to reproduce the issue on my end to confirm this.

Thanks!

**Comment by ollyculverhouse** [comment]
On one of my other playbooks (not the one that has the code above), it happened once or twice, then disappeared.

This one it seemed to happen consistently, every time the playbook was run on a brand new AWS instance. Until of course the pause was put in place.

Running ansible 2.2.0.0

**Comment by olivielpeau** [comment]
Thanks for the additional info! I'll spend some time to try and reproduce the issue...

**Comment by pirackr** [comment]
I got the same issue with Ansible 2.2.0 but for previous step:
```
TASK [Datadog.datadog : apt_repository] ****************************************
fatal: [xxxxxxxx]: FAILED! => {"changed": false, "failed": true, "msg": "[Errno 13] Permission denied: '/etc/apt/.sources.list-5m8YVc'"}
	to retry, use: --limit @/home/xxxxxxx/ansible/production.retry
```
I'm trying to setup datadog for an Ubuntu 16.04 server as well.

**Comment by olivielpeau** [comment]
@pirackr Your issue could be related to #41, could you try upgrading to Ansible 2.2.1 or downgrading to a 2.1.x release?

**Comment by pirackr** [comment]
I will check, thanks @olivielpeau

**Comment by hush-hush** [comment]
Hi @pirackr and @ollyculverhouse ,

I guess this issue was solved, so I'll close this issue.
But feel free to reopen if needed.

Thanks.
