### ISSUE TITLE
fix_6_14.ps1 script tries to download even when applicable agent versions are not being installed

### ISSUE THREAD

**Issue by lognarly** [DataDog/ansible-datadog#397]
Why does the task under pkg-windows.yaml still run to download this script, even if agent version 7 if being installed? Can there be a var/flag put in place to either skip this step, or add in a check to only perform the download when that agent version is being installed? We have systems with limited internet access we are deploying to that can't reach this file, but we aren't even installing this version of the agent. We would prefer to not have to clone your repo internally to modify this, because then we have to keep it in sync when future changes are made to this public repo. Any thoughts?

**Comment by lognarly** [comment]
Would setting datadog_windows_614_fix_script_url in the play vars override this if we host internally?

**Comment by bkabrda** [comment]
Hey 👋  thanks for opening this issue report. You're absolutely right that for vast majority of users this is not necessary to download at this point, given that 6.14.0 and 6.14.1 have been blacklisted for such a long time. I will however need to figure out how many users might still be affected by removing this. For now, you can set `datadog_windows_614_fix_script_url` to a different url (and you could probably even provide a completely empty script at that url to make things faster).

Let me know if setting the custom URL works for you now. In the meanwhile, I'll try to see if we could remove this altogether or at least put this behind a boolean config value or run this only on certain set of versions following 6.14 or something like that.

**Comment by albertvaka** [comment]
I think we could remove that logic in an upcoming version of the role. 6.14 is quite old already, so I doubt anyone will try to install it using the current version of the role.

**Comment by bkabrda** [comment]
I implemented a switch to turn this off (but it's still on by default). To be released in the next version soon.
