### ISSUE TITLE
Question about a collection

### ISSUE THREAD

**Issue by rockaut** [DataDog/ansible-datadog#424]
Hello all,

quick question: is there any plan to bring an official datadog ansible collection with more than "just" the datadog agent role? Like with integrating the Datadog API for Dashboards and so on but also for some of the agents dogshell things?

If not, how is the stance on an community.datadog creation over at https://github.com/orgs/ansible-community ?

Thanks, Markus

**Comment by bkabrda** [comment]
Hi 👋 we currently have no plans for this, but I am curious to hear more about your usecases.

* In terms of API for Dashboards etc, our go-to tool is [Datadog Terraform Provider](https://registry.terraform.io/providers/DataDog/datadog/latest/docs), which is intended and works best for manipulating these kinds of APIs. Would that work for you? If not, is there something you're missing in it, or are you just looking to have everything in Ansible?
* What kind of dogshell things are you interested in?

I'm sure that once I understand your usecases better, we can figure out a good solution.
Thanks!

**Comment by rockaut** [comment]
Heja,

- we have a lot of Ansible already running and especially we in monitoring are using it for most things. That said I'm not opposed to use Terraform it would just be nicer to have it in one solution.

We aren't using DD at this point but we are evaluating it and as I'm also involved in some other ansible community repos I just wanted to look what the stand here is. I will close this for now, but maybe come back if we decide on using dd.

Thx

**Comment by bkabrda** [comment]
@rockaut sure. I am not directly opposed to adding these things to the playbook, I'm just trying to see if it would make sense for you to use something that already works and is used by a lot of people.

Do let me know if you have further questions/comments/suggestions. Thanks!
