### ISSUE TITLE
Bug: Role fails in check mode with `object has no attribute 'gid'`

### ISSUE THREAD

**Issue by henti** [DataDog/ansible-datadog#439]
When running the role in check mode using `ansible-playbook datadog.yml  -CD` with datadog.yml

```
- name: Deploy datadog agents
  hosts: datadog_host
  become: yes
  roles:
    - role: datadog-agent
```
I get this error. 

```
MSG:

The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'gid'

The error appears to be in '/home/henti/src/code/.github/infrastructure/ansible/roles/datadog-agent/tasks/agent-macos.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Load user group data
  ^ here
```

This is due to the `Load user data` step which loads the user data from executing `dscacheutil` not executing. This can be fixed by adding `check_mode: no` to `tasks/agent-macos.ym` at [line 10](https://github.com/DataDog/ansible-datadog/blob/main/tasks/agent-macos.yml#L10)

**Comment by bkabrda** [comment]
Hi 👋 thanks for the bug report. I'll open a PR to fix this.
