### ISSUE TITLE
datadog_checks missing for Linux agents above version 5.x

### ISSUE THREAD

**Issue by jeffbilder** [DataDog/ansible-datadog#470]
In reviewing the tasks, I noticed that only agent5 has the configuration building for the conf.d configurations.  When using datadog_checks for agents above 5.x, they do not create the configurations under /etc/datadog-agent/conf.d.

**Comment by jeffbilder** [comment]
Can someone take a look at this PR?  We really need this feature internally.

**Comment by bkabrda** [comment]
Hi :wave: first of all, sorry for the long wait.

I think the tasks that you're looking for are at https://github.com/DataDog/ansible-datadog/blob/main/tasks/_agent-linux-macos-shared.yml#L21 and should be used for Agent 6/7. If things don't seem to work fine for you, could you please post a reproducer configuration as well as datadog role version you're using and the exact problem that you're hitting? Thanks!

**Comment by jeffbilder** [comment]
Thanks this is fixed!
