### ISSUE TITLE
Was the  "Agent on host, app in containers" possibility of injecting APM overlooked?

### ISSUE THREAD

**Issue by maxiangelo** [DataDog/ansible-datadog#514]
As stated in the [official documentation,](https://docs.datadoghq.com/tracing/trace_collection/library_injection_local/#?tab=agentonhostappincontainers) it's a possibility to have the agent running on the host and inject the tracing library into containers.  
As far as I can see from my tests, this is not yet covered with the `host, container or all` option of the `datadog_apm_instrumentation_enabled` variable of the Ansible script, right? :) 

#481

**Comment by jonbodner** [comment]
Question: does the `all` option work for agent on host, services in container? It should.

**Comment by maxiangelo** [comment]
Hey, yes, with all it worked.
