### ISSUE TITLE
Can a oom_kill_enabled option be added to config options?

### ISSUE THREAD

**Issue by ckolos-work** [DataDog/ansible-datadog#522]
In  the documentation [oom_kill/#configuration](https://docs.datadoghq.com/integrations/oom_kill/#configuration), it's stated that `/etc/datadog-agent/system-probe.conf` file must have the line `oom_kill_enabled: true` present (in conjunction with configuring `conf.d/oom_kill.d/conf.yaml`) to monitor for oom_kill events. However there is no corresponding config option in dd role varaibles to do this. I can see only the following options for system_probe_config:

```
>>{{- if (eq .OS "windows")}}
>>    sysprobe_socket: localhost:3333
>>{{else}}
>>    sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
>>{{ end }}
>>    log_file: /var/log/datadog/system-probe.log
>>    language_detection:
>>      enabled: false
>>{{- if .InternalProfiling -}}
>>    internal_profiling:
>>      enabled: false
>>      enabled: false
>>      thresholds:
>>        500MB: gc
>>        50%: profile
>>      pressure_levels:
>>        medium: gc
```

Any chance an `oom_kill_enabled` option can be added here? Apologies if I've missed something simple...

**Comment by bkabrda** [comment]
:wave: Hi, have you tried adding using the following in your vars?
```
system_probe_config:
  enable_oom_kill: true
```

That should make it work AFAICS.

**Comment by alopezz** [comment]
@ckolos-work hopefully the provided solution was helpful? Given the inactivity, I'm closing this, but feel free to reopen if it's still not solved!
