### ISSUE TITLE
A shell and a home folder

### ISSUE THREAD

**Issue by mliljedahl** [DataDog/ansible-datadog#544]
Guess this is not an issue with the actual ansible role (but it could be changed byt the role). Is there any reason for creating the datadog agent user with a shell and a home folder? This is at least the fact in Redhat. I see no reason for the user to have this and have updated the user in our setup to exclude shell and home folder, but I might be missing something? If wanted I can provide a PR for the change.

**Comment by bkabrda** [comment]
Hi :wave: do you have a case where the `dd-agent` user has a home folder and shell?

This role doesn't touch any of that whatsoever. The user is created as part of the preinst RPM script (talking about RPMs specifically, but it's basically the same for DEBs) which you can see [here](https://github.com/DataDog/datadog-agent/blob/main/omnibus/package-scripts/agent-rpm/preinst#L50). As you can see for yourself, it's created as a system account, so should have no home folder, and it uses `/sbin/nologin` as shell.

If you have the `dd-agent` user created with a home folder and shell, can you share more details about how you first installed the Agent? That might give us a clue as to what went wrong.

**Comment by alopezz** [comment]
Closing it for inactivity, more so given that the issue doesn't seem to be the Ansible role.
