### ISSUE TITLE
Error when installing the datadog agent - Exception calling \"CreateProcess\" with \"7\" argument(s): \"CreateProcessW() failed (%1 is not a valid Win32 application, Win32ErrorCode 193 - 0x000000C1)\"

### ISSUE THREAD

**Issue by tirbaklien** [DataDog/ansible-datadog#549]
We have an issue when trying to install the datadog agent through ansible on some of our servers. The error message (with -vvv):

> The full traceback is:
> Exception calling "CreateProcess" with "7" argument(s): "CreateProcessW() failed (%1 is not a valid Win32 application, Win32ErrorCode 193 - 0x000000C1)"
> At line:678 char:15
> +     $result = Start-AnsibleWindowsProcess @commandArgs
> +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Start-AnsibleWindowsProcess], MethodInvocationException
>     + FullyQualifiedErrorId : Win32Exception,Start-AnsibleWindowsProcess
>  
> ScriptStackTrace:
> at Start-AnsibleWindowsProcess, <No file>: line 230
> at Invoke-Executable, <No file>: line 678
> at <ScriptBlock>, <No file>: line 1327
> at <ScriptBlock>, <No file>: line 1488
>  
> System.Management.Automation.MethodInvocationException: Exception calling "CreateProcess" with "7" argument(s): "CreateProcessW() failed (%1 is not a valid Win32 application, Win32ErrorCode 193 - 0x000000C1)" ---> ansible_collections.ansible.windows.plugins.module_utils.Process.Win32Exception: CreateProcessW() failed (%1 is not a valid Win32 application, Win32ErrorCode 193 - 0x000000C1)
>    at ansible_collections.ansible.windows.plugins.module_utils.Process.ProcessUtil.NativeCreateProcess(String applicationName, String commandLine, SecurityAttributes processAttributes, SecurityAttributes threadAttributes, Boolean inheritHandles, ProcessCreationFlags creationFlags, IDictionary environment, String currentDirectory, StartupInfo startupInfo) in c:\Users\username\AppData\Local\Temp\s1s6vqwo.1.cs:line 556
>    at ansible_collections.ansible.windows.plugins.module_utils.Process.ProcessUtil.CreateProcess(String lpApplicationName, String lpCommandLine, String lpCurrentDirectory, IDictionary environment, Byte[] stdin, String outputEncoding, Boolean waitChildren) in c:\Users\username\AppData\Local\Temp\s1s6vqwo.1.cs:line 520
>    at CallSite.Target(Closure , CallSite , Type , Object , String , String , Object , Object , String , SwitchParameter )
>    --- End of inner exception stack trace ---
>    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
>    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
>    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
>    at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
>    at System.Management.Automation.CommandProcessorBase.Complete()
> fatal: [servername]: FAILED! => {
>     "changed": false,
>     "msg": "Unhandled exception while executing module: Exception calling \"CreateProcess\" with \"7\" argument(s): \"CreateProcessW() failed (%1 is not a valid Win32 application, Win32ErrorCode 193 - 0x000000C1)\""
> }

I try to install it the exact same way on all of our servers, but on some, i encounter this issue. The OS is windows. If i try to install it manually on the servers, everything works fine.

**Comment by alopezz** [comment]
Hi 👋 , if the issue still persists, please contact [Datadog Support](https://help.datadoghq.com/) so that you can provide us more detail and we can help you better.
