### ISSUE TITLE
Role not compatible with Ansible versions higher than v6.7.0

### ISSUE THREAD

**Issue by sriemschuessel** [DataDog/ansible-datadog#564]
## Problem
I'm currently blocked to use the latest version of the role to install the Datadog Agent on machines with SLES 12 SP5 when using any Ansible version higher than v6.7.0 (Ansible-core 2.13).

### Reason
The task in https://github.com/DataDog/ansible-datadog/blob/4.22.0/tasks/pkg-suse.yml#L133-L139 and perhaps more rely on the deprecated and in v7 and higher removed feature to mute Ansible warnings. 

See Ansible 7 porting guide: 
* https://github.com/ansible/ansible-documentation/blob/devel/docs/docsite/rst/porting_guides/porting_guide_7.rst?plain=1#L940

### Affected versions
* Datadog role **datadog.datadog 4.21.0 / 2023-12-04**

--- 

I hope this is detailed enough for you to fix the issue. Thanks

**Comment by alopezz** [comment]
Thanks for reporting this! A fix has been implemented, I'll try to get the release out as soon as possible.
