### ISSUE TITLE
psutil needed with omnibus install?

### ISSUE THREAD

**Issue by bakins** [DataDog/ansible-datadog#6]

**Comment by bakins** [comment]
It appears to be installed: `/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil`

**Comment by miketheman** [comment]
Should not be needed as of 5.x - Docs updated in https://github.com/DataDog/documentation/issues/225

**Comment by bakins** [comment]
Thanks @miketheman I'll go ahead and merge https://github.com/bakins/ansible-datadog/pull/7
