### ISSUE TITLE
Add possibility to change YUM repo url

### ISSUE THREAD

**Issue by aairey** [DataDog/ansible-datadog#65]
Can you provide some default variables for the yum repos?
Just like with apt. so that we can override these with URL and key from our local mirror.

These vars should be sufficient:

- datadog_yum_url
- datadog_yum_key
- datadog_yum_enabled

**Comment by olivielpeau** [comment]
Hi @aairey and thanks for your suggestion. This definitely makes sense.

I think we'll also need a `datadog_yum_key_new` var to override the URL of the "new" gpgkey that the role installs on top of the one defined in the `repo` file.

I'm not sure I understand what `datadog_yum_enabled` would do, could you elaborate on that?

**Comment by aairey** [comment]
To set the repository to enabled/disabled by default.

It is a setting within the yum repo file: `enabled=1`.

This makes sense if you install the public repo and you do not want to auto
update the datadog-agent package on a `yum update`.

You can override it again by specifying `yum update -y --enablerepo=datadog
datadog-agent`.

I think you also have the `enablerepo` argument on the yum ansible module.
(Not sure, on phone now)

**Comment by aairey** [comment]
It appears that the open PR #48 solves the `datadog_yum_url` missing variable mentioned above.
In the PR `datadog_yum_repo` is added with the same purpose.

This would already solve the problem I am having, so we can point to an internal mirror.

**Comment by olivielpeau** [comment]
This is implemented by #80. Thanks @aairey!

The role also supports pinning the version of the agent, I'd recommend that to avoid auto-upgrading the agent to the latest version provided by the repo when yum's cache is updated
