### ISSUE TITLE
Ability to set hostname?

### ISSUE THREAD

**Issue by seenickcode** [DataDog/ansible-datadog#74]
Hello.  I see here that one can set the hostname in the datadog config (https://help.datadoghq.com/hc/en-us/articles/203037179).  Is this possible via this playbook?

**Comment by jeffwidman** [comment]
Sure, just set it in the agent configuration file.

**Comment by seenickcode** [comment]
Greetings @jeffwidman .. the agent config file's template doesn't support this particular setting.  Possible to add support for it?  I'd rather not fork + customize the template as I do not want to have to miss out on updates to the original repo.

**Comment by jeffwidman** [comment]
Can you not add it to the `datadog_config` role variable?

https://github.com/DataDog/ansible-datadog/blob/07ac223dbfd9ea8792dd339b0cd8102b188be361/templates/datadog.conf.j2#L17-L22

**Comment by seenickcode** [comment]
Perfect. Can't believe I didn't realize that thank you.  

For everyone else, here's what I added:

```
datadog_config:
  hostname: "{{ inventory_hostname }}"
```
