### ISSUE TITLE
Adding config files to conf.d

### ISSUE THREAD

**Issue by eugenemiretsky** [DataDog/ansible-datadog#76]
Is there an easy way to add/enable specific yaml configs in conf.d. For example, I want enabled haproxy, I would usually just copy haproxy.yaml.example to haproxy.yaml

**Comment by jeffwidman** [comment]
How would you map which hosts get which config files? Ie, enable the redis checks on redis machines but not on other machines...

**Comment by eugenemiretsky** [comment]
@jeffkwiat: If you want to used the config existing examples without modifying them could pass it as a parameter from the Redis,Cassandra,etc playbook playbook.

**Comment by jeffkwiat** [comment]
Hey, @eugenemiretsky, I think you meant your previous message for @jeffwidman Thanks!

**Comment by olivielpeau** [comment]
Hi @eugenemiretsky!

Currently there's no other way to enable checks with this role than to use the `datadog_checks` var as described in the README.

In the general case, `.yaml.example` are not meant to be used programmatically but are only there to provide docs on the options required/supported by each check. You'll have to read the example file of each check you want to enable and set up the `datadog_checks` var accordingly.

I don't think we'll revisit this in the near future, unless you have a good idea of how we could implement this in the general case :)

I'm going to go ahead and close this issue , but please respond here/re-open it if you need more info/have any suggestions, thanks!
