### ISSUE TITLE
RFE: Add support for installing datadog-agent from source

### ISSUE THREAD

**Issue by jaredledvina** [DataDog/ansible-datadog#82]
Specifically, for systems where there is not a pre-built package available, being able to install from source, would be perfect. 

Example: 
https://help.datadoghq.com/hc/en-us/articles/208163513-Deploying-the-Agent-on-RaspberryPI

**Comment by olivielpeau** [comment]
Hi @jaredledvina and thanks for opening this issue!

I'm going to put your request in triage to gauge the demand for this. Implementing the install from source could take some time so I want to make sure there's a lot of demand for it first.

Feel free to open a PR yourself if you have time to implement this ;)

**Comment by jaredledvina** [comment]
Hey @olivielpeau,

Totally understand, maybe a 'quick' workaround would be to have a `datadog_external_install` flag that will skip the repo setup/install tasks. The idea being that if the DataDog agent was installed from another source, this role will still configure it and such but not manage the installation bits.

**Comment by hush-hush** [comment]
Hi @jaredledvina,

The source install is no longer possible with the latest version of the agent (version 6 and above), since it was rewritten in Go. We continue to publish update of the agent5 even if the focus has shifted to version6.

That being said I think your proposition to have an option to skip the install step would be useful for both versions of the agent.

I'll try to open a PR soon unless you have time to implement it ;).

**Comment by jaredledvina** [comment]
Hey @hush-hush,

Ah very interesting, are there going to be native packages for the RaspberryPi available for the v6 agent? If so, we can also just close this, that's the only platform I'm running the agent on that doesn't have a package up.

**Comment by hush-hush** [comment]
We don't have native package for RaspberryPi (or any ARM) yet.

In the meanwhile the agent6 `puppy` version is known to run smoothly on ARM: see https://github.com/DataDog/datadog-agent/issues/1069.

As explained in the first answer from masci: `Puppy Agent` is a lightweight version of the full Agent that cross compiles to different platforms at the price of having fewer features (most notably, the Python engine is missing, meaning you can't execute Python checks on Puppy). 
Here is a list of the different [module in agent6](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/agent_build.md#be-modular), the puppy agent only includes `zlib`.

I don't know if that would answer your needs. In any case I'll add the option to ansible to skip the install.
