### ISSUE TITLE
Integration configuration files are installed to the wrong location for agent v6+

### ISSUE THREAD

**Issue by DownRangeDevOps** [DataDog/ansible-datadog#94]
`dest: "/etc/datadog-agent/conf.d/{{ item }}.yaml"`

should be:

`dest: "/etc/datadog-agent/{{ item }}.d/conf.yaml"`

According to the [docs](https://docs.datadoghq.com/logs/#agent-checks).

**Comment by hush-hush** [comment]
Hi @techFishIO,

Thanks for raising this issue. Even if the agent6 can handle both way I agree it make more sens to follow the documentation.
The fix has been merged and will be available in `2.0.4` (it will be release this week).

Closing the issue, but feel free to reopen it if needed
